apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: backend
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 4200
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: backend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        tier: frontend
        track: stable
    spec:
      containers:
      - name: frontend
        image: ksivled/frontend
